server:
  port: 7778

spring:
  application:
    name: customers
  profiles:
    active: production
  datasource:
    url: jdbc:postgresql://localhost:5433/customersDb
    platform: postgres
    continue-on-error: true
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
