server:
  port: 7777

spring:
  application:
    name: accounts
  profiles:
    active: production
  datasource:
    url: jdbc:postgresql://localhost:5432/accountsDb
    platform: postgres
    continue-on-error: true
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
